//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMvcDmeo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tShoppingCart
    {
        public int fId { get; set; }
        public string fDate { get; set; }
        public Nullable<int> fCustomerId { get; set; }
        public Nullable<int> fProductId { get; set; }
        public Nullable<int> fCount { get; set; }
        public Nullable<decimal> fPrice { get; set; }
    }
}
